apiVersion: v1
kind: PersistentVolume
metadata:
  name: workflow-pv
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/data"