apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workflow-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: workflow-pv