apiVersion: v1
kind: PersistentVolume
metadata:
  name: workflow-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: cinder.csi.openstack.org
    ## EDIT BELOW: replace the placeholder 'xxxxxxxx-xxxx-xxxx' with your volumes UUID
    volumeHandle: xxxxxxxx-xxxx-xxxx
  storageClassName: cinder-sc
  claimRef:
    name: workflow-pvc
    namespace: argo